python_library(
    dependencies=[
        "3rdparty/python:behave",
        "3rdparty/python:generic-behave",
        "3rdparty/python:selenium",
    ],
    sources=["ns_page_objects/**/*"],
    tags={".", "code", "python"},
)
